spring:
  application:
    name: user-api  # The name of your application (to register with Eureka)

eureka:
  client:
    register-with-eureka: false  
    fetch-registry: false        
    prefer-ip-address: true    

